# Square

This mathematical function helps user to calculate square value of each element in the array

In [1]:
# square () function

import numpy as np

arr1 = [1, -3, 15, -466]
print ("Square Value of arr1 : \n", np.square(arr1))

arr2 = [23,-56]
print ("\nSquare Value of arr2 : ", np.square(arr2))

Square Value of arr1 : 
 [     1      9    225 217156]

Square Value of arr2 :  [ 529 3136]


# sqrt()

Return the non-negative squqre root of an array,element-wise.

In [2]:
# sqrt () function

import numpy as np
arr1 = [1, -3, 15, -466]
print ("Square Value of arr1 : \n", np.square(arr1))

Square Value of arr1 : 
 [     1      9    225 217156]


# cbrt

This mathematical function helps user to calculate Cube root of x for all x being the array elements.

In [4]:
# cbrt () function

import numpy as np

arr1 = [1, 27000, 64, -1000]
print ("cbrt Value of arr1 : \n", np.cbrt(arr1))

arr2 = [1024 ,-128]
print ("\ncbrt Value of arr2 : ", np.cbrt(arr2))


cbrt Value of arr1 : 
 [  1.  30.   4. -10.]

cbrt Value of arr2 :  [10.0793684 -5.0396842]


# Power()

Array element from first array is raised to the power of element from second element.

Both arr1 and arr2 must have same shape and each element in arr1 must be raised to corresponding +ve value from arr2. otherwise it will raise a ValueeError.

In [5]:
# power() function
import numpy as np

#input_array
arr1 = [2, 2, 2, 2, 2]
arr2 = [2, 3, 4, 5, 6]
print ("arr1 : ", arr1)
print ("arr1 : ", arr2)

# output_array
out = np.power(arr1, arr2)
print ("\nOutput array : ", out)

arr1 :  [2, 2, 2, 2, 2]
arr1 :  [2, 3, 4, 5, 6]

Output array :  [ 4  8 16 32 64]


# absolute

This mathematical function helps user to calculate absolute of each element in the array.

For complex input, a + lb, the absolute value is \sqrt{a^2 + b^2}

In [6]:
# absolute () function

import numpy as np

arr1 = [1, -3, 15, -466]
print ("Absolute value of arr1 : \n",
       np.absolute(arr1))

arr2 = [23 , -56]
print ("Absolute value of arr2 : \n",
       np.absolute(arr2))

Absolute value of arr1 : 
 [  1   3  15 466]
Absolute value of arr2 : 
 [23 56]


In [7]:
# absolute () function on complex numbers

import numpy as np

a =  4 + 3j
print("Absolute(4 + 3j) : ",
      np.absolute(a))

b = 16 + 13j
print("Absolute value(16 + 13j) : ",
      np.absolute(b))


Absolute(4 + 3j) :  5.0
Absolute value(16 + 13j) :  20.615528128088304
